name: Cortex Security Pipeline - Image Scan

on:
  push:
    branches:
      - main

jobs:
  build-and-scan:
    name: Construir y Escanear Contenedor
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el código
        uses: actions/checkout@v4

      - name: Descargar e Instalar cortexcli
        run: |
          set -e
          crtx_resp=$(curl -s "${{ secrets.CORTEX_API_URL }}/public_api/v1/unified-cli/releases/download-link?os=linux&architecture=amd64" \
            -H "x-xdr-auth-id: ${{ secrets.CORTEX_API_KEY_ID }}" \
            -H "Authorization: ${{ secrets.CORTEX_API_KEY }}")
          
          crtx_url=$(echo "$crtx_resp" | jq -r ".signed_url")
          if [ -z "$crtx_url" ] || [ "$crtx_url" = "null" ]; then
            echo "::error::No se pudo obtener el signed_url."
            exit 1
          fi
          
          curl -s -o cortexcli "$crtx_url"
          chmod +x cortexcli
          sudo mv cortexcli /usr/local/bin/cortexcli
          cortexcli --version

      - name: Construir la imagen Docker
        run: |
          # Construimos la imagen y la etiquetamos con el ID único del commit
          docker build -t mi-app-debian:${{ github.sha }} .
          echo "Imagen local construida con éxito."

      - name: 2. Cortex Scan - Escaneo de la Imagen
        run: |
          # Imprimimos el manual de ayuda para ver las banderas exactas que acepta tu versión
          cortexcli image scan --help
          
          echo "-----------------------------------"
          echo "Iniciando escaneo (Intento posicional)..."
          
          set -e
          # Intento 1: Pasamos el nombre de la imagen directamente al final, sin la palabra --image
          cortexcli \
            --api-base-url "${{ secrets.CORTEX_API_URL }}" \
            --api-key "${{ secrets.CORTEX_API_KEY }}" \
            --api-key-id "${{ secrets.CORTEX_API_KEY_ID }}" \
            image scan \
            --source "CORTEX_CLI" \
            "mi-app-debian:${{ github.sha }}"
