- name: Construir imagen Docker
        run: |
          # El nombre debe ir obligatoriamente en minúsculas para Docker
          docker build -t calo-cortexcli-prueba:latest .
          echo "¡Imagen calo-cortexcli-prueba construida localmente!"

      - name: Cortex Scan - Escaneo de la Imagen (CVEs)
        run: |
          set -e
          echo "Buscando vulnerabilidades en la imagen calo-cortexcli-prueba..."
          cortexcli \
            --api-base-url "${{ secrets.CORTEX_API_URL }}" \
            --api-key "${{ secrets.CORTEX_API_KEY }}" \
            --api-key-id "${{ secrets.CORTEX_API_KEY_ID }}" \
            image scan \
            --ci-pipeline-id "${{ github.repository }}" \
            --ci-build-id "${{ github.run_id }}" \
            --name "Calo-CortexCLI-prueba" \
            calo-cortexcli-prueba:latest

      - name: 3. Despliegue Automático en Docker Desktop
        run: |
          echo "Buscando y removiendo versiones antiguas del contenedor si existen..."
          docker rm -f Calo-CortexCLI-prueba || true
          
          echo "Lanzando el nuevo contenedor en Docker Desktop..."
          # El flag --name sí acepta mayúsculas para el contenedor final en Docker Desktop
          docker run -d -p 8080:80 --name Calo-CortexCLI-prueba calo-cortexcli-prueba:latest
          
          echo "¡Despliegue finalizado! Revisa tu aplicación Docker Desktop."
